# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=300)),
                ('filesize', models.IntegerField(default=0)),
                ('key', models.CharField(max_length=300)),
                ('uploaddate', models.DateTimeField(auto_now=True)),
                ('browserable', models.BooleanField(default=True)),
            ],
        ),
    ]
