# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2020-03-18 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='filesize',
            field=models.BigIntegerField(default=0),
        ),
    ]
